spring:
  application:
    name: trainingSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  logging:
    level:
      liquibase: INFO
      org.springframework.jdbc.core: DEBUG